version: '2.3'

services:

  task:
    container_name: pwn_speedrun_case4
    image: pwn_speedrun_case4_img

    build: service
    restart: always
    ports:
      - 33048:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
